#### 1) Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[9,8,7],
     [6,5,4],
     [3,2,1]]

result = np.array(x) + np.array(y)
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [2]:
# Method 2 using for loop

x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[9,8,7],
     [6,5,4],
     [3,2,1]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(x)):
    for j in range(len(x[0])):
        result [i][j] = x[i][j] + y[i][j]
for r in result:
    print(r)
        

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#### 2) Write a Python Program to Multiply Two Matrices?

In [3]:
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[9,8,7],
     [6,5,4],
     [3,2,1]]

result = np.array(x)@np.array(y)       # @ is used to matmul in numpy
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [4]:
np.dot(x,y)                        #This is also built in method in numpy for matmul

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [5]:
# Method using for loop

x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[9,8,7],
     [6,5,4],
     [3,2,1]]

res = [[0 for x in range(3)] for y in range(3)]

for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            res[i][j] += x[i][k] * y[k][j]
print(res)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


#### 3) Write a Python Program to Transpose a Matrix?

In [6]:
#Using for loop
A = [[1,2,3],
    [4,5,6]]

T = [[0 for A in range(2)] for A in range(3)]
for i in range(len(A)):
    for j in range(len(A[0])):
        T[j][i] = A[i][j]
for i in T:
    print(i)

[1, 4]
[2, 5]
[3, 6]


In [7]:
#using list comprehenstion
A = [[1,2,3],
    [4,5,6]]

[[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

[[1, 4], [2, 5], [3, 6]]

#### 4) Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
def func(S):
    W = S.split()
    for i in range(len(W)):
        W[i] = W[i].lower()
    S = sorted(W)
    print(' '.join(S))

In [9]:
func(S = "the Quick brown fox jumPs over the lazY Dog")

brown dog fox jumps lazy over quick the the


#### 5) Write a Python Program to Remove Punctuation From a String?

In [10]:

test_str = "Gfg, is best : for ! Geeks @! %^& ;"

print("The original string is : " + test_str)

punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
 

for ele in test_str:
    if ele in punc:
        test_str = test_str.replace(ele, "")
print("The string after punctuation filter : " + test_str)

The original string is : Gfg, is best : for ! Geeks @! %^& ;
The string after punctuation filter : Gfg is best  for  Geeks   
