In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5,6]


In [4]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
l1 = [4,5,6,7,"sudh",34.565,True]

In [6]:
a1 = np.array(l1)

In [7]:
a2 = np.array([[1,2,3],[4,5,6]])

In [8]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [9]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
a1.size

7

In [16]:
a2.size

6

In [17]:
a3.size

9

In [18]:
a1.shape

(7,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape

(1, 3, 3)

In [21]:
np.random.randint(2,50,(3,4))

array([[47, 16, 25,  7],
       [15, 42, 25, 15],
       [17, 39, 34, 32]])

In [22]:
np.random.randint(2,50,(2,3,4))

array([[[22, 12,  6,  5],
        [45, 27, 12, 37],
        [10, 47, 11, 23]],

       [[14, 45, 12, 10],
        [14, 28, 42, 46],
        [20, 47, 27, 13]]])

In [23]:
np.random.rand(2,3)

array([[0.34734064, 0.98072019, 0.2005253 ],
       [0.1278598 , 0.46617084, 0.60840238]])

In [24]:
a4 = np.random.randn(4,4)

In [25]:
a4

array([[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226],
       [-1.91777363,  0.32989709, -1.08628736, -0.64946985],
       [ 0.08928163, -0.13070459, -0.26946364, -1.31433287],
       [ 0.30336499,  0.1389327 , -1.39087951,  1.40394417]])

In [26]:
a4.reshape(2,8)

array([[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226, -1.91777363,
         0.32989709, -1.08628736, -0.64946985],
       [ 0.08928163, -0.13070459, -0.26946364, -1.31433287,  0.30336499,
         0.1389327 , -1.39087951,  1.40394417]])

In [27]:
a4.reshape(8,2)

array([[ 1.54854338,  1.04041246],
       [ 0.8156525 , -0.94194226],
       [-1.91777363,  0.32989709],
       [-1.08628736, -0.64946985],
       [ 0.08928163, -0.13070459],
       [-0.26946364, -1.31433287],
       [ 0.30336499,  0.1389327 ],
       [-1.39087951,  1.40394417]])

In [28]:
a4.reshape(1,16)

array([[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226, -1.91777363,
         0.32989709, -1.08628736, -0.64946985,  0.08928163, -0.13070459,
        -0.26946364, -1.31433287,  0.30336499,  0.1389327 , -1.39087951,
         1.40394417]])

In [29]:
a4.reshape(16,1)

array([[ 1.54854338],
       [ 1.04041246],
       [ 0.8156525 ],
       [-0.94194226],
       [-1.91777363],
       [ 0.32989709],
       [-1.08628736],
       [-0.64946985],
       [ 0.08928163],
       [-0.13070459],
       [-0.26946364],
       [-1.31433287],
       [ 0.30336499],
       [ 0.1389327 ],
       [-1.39087951],
       [ 1.40394417]])

In [30]:
a4.reshape(2,-1)

array([[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226, -1.91777363,
         0.32989709, -1.08628736, -0.64946985],
       [ 0.08928163, -0.13070459, -0.26946364, -1.31433287,  0.30336499,
         0.1389327 , -1.39087951,  1.40394417]])

In [31]:
a4.reshape(2,2,4)

array([[[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226],
        [-1.91777363,  0.32989709, -1.08628736, -0.64946985]],

       [[ 0.08928163, -0.13070459, -0.26946364, -1.31433287],
        [ 0.30336499,  0.1389327 , -1.39087951,  1.40394417]]])

In [32]:
a4.reshape(1,1,1,1,1,1,2,2,4)

array([[[[[[[[[ 1.54854338,  1.04041246,  0.8156525 , -0.94194226],
              [-1.91777363,  0.32989709, -1.08628736, -0.64946985]],

             [[ 0.08928163, -0.13070459, -0.26946364, -1.31433287],
              [ 0.30336499,  0.1389327 , -1.39087951,  1.40394417]]]]]]]]])

In [33]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [34]:
a1[0]

'4'

In [35]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [36]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [37]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [38]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2[0]

array([1, 2, 3])

In [40]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [41]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [42]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [43]:
a5 = np.random.randint(2,90,(6,5))

In [44]:
a5

array([[59, 22, 81, 16, 42],
       [32, 46, 18, 37, 31],
       [83, 55,  6,  3, 26],
       [34, 25, 65, 56, 37],
       [65,  8, 73, 25, 21],
       [34, 86, 52, 85, 42]])

In [45]:
a5[a5>40]

array([59, 81, 42, 46, 83, 55, 65, 56, 65, 73, 86, 52, 85, 42])

In [46]:
a5

array([[59, 22, 81, 16, 42],
       [32, 46, 18, 37, 31],
       [83, 55,  6,  3, 26],
       [34, 25, 65, 56, 37],
       [65,  8, 73, 25, 21],
       [34, 86, 52, 85, 42]])

In [47]:
a5[0,1]=100

In [48]:
a5

array([[ 59, 100,  81,  16,  42],
       [ 32,  46,  18,  37,  31],
       [ 83,  55,   6,   3,  26],
       [ 34,  25,  65,  56,  37],
       [ 65,   8,  73,  25,  21],
       [ 34,  86,  52,  85,  42]])

In [54]:
a6 = np.random.randint(0,3,(3,3))

In [50]:
a7 = np.random.randint(0,3,(3,3))

In [55]:
a6

array([[2, 0, 1],
       [1, 1, 0],
       [1, 2, 1]])

In [52]:
a7

array([[2, 2, 1],
       [1, 2, 0],
       [2, 1, 2]])

In [56]:
a6*a7

array([[4, 0, 1],
       [1, 2, 0],
       [2, 2, 2]])

In [57]:
a6@a7

array([[6, 5, 4],
       [3, 4, 1],
       [6, 7, 3]])

In [59]:
a6+100

array([[102, 100, 101],
       [101, 101, 100],
       [101, 102, 101]])

In [60]:
a6*2

array([[4, 0, 2],
       [2, 2, 0],
       [2, 4, 2]])

In [61]:
a6/0

C:\Users\ADMINI~1.UPT\AppData\Local\Temp/ipykernel_8580/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\ADMINI~1.UPT\AppData\Local\Temp/ipykernel_8580/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [inf, inf, nan],
       [inf, inf, inf]])

In [62]:
a6

array([[2, 0, 1],
       [1, 1, 0],
       [1, 2, 1]])

In [63]:
a6**3

array([[8, 0, 1],
       [1, 1, 0],
       [1, 8, 1]], dtype=int32)

In [66]:
a8 = np.zeros((4,4))

In [67]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
a9 = np.ones((4,5))

In [70]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [72]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [73]:
a9 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
np.array([[1,2,3,4]]) 

array([[1, 2, 3, 4]])

In [80]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [81]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [82]:
a6

array([[2, 0, 1],
       [1, 1, 0],
       [1, 2, 1]])

In [83]:
a6.T

array([[2, 1, 1],
       [0, 1, 2],
       [1, 0, 1]])

In [84]:
np.sqrt(a5)

array([[ 7.68114575, 10.        ,  9.        ,  4.        ,  6.4807407 ],
       [ 5.65685425,  6.78232998,  4.24264069,  6.08276253,  5.56776436],
       [ 9.11043358,  7.41619849,  2.44948974,  1.73205081,  5.09901951],
       [ 5.83095189,  5.        ,  8.06225775,  7.48331477,  6.08276253],
       [ 8.06225775,  2.82842712,  8.54400375,  5.        ,  4.58257569],
       [ 5.83095189,  9.2736185 ,  7.21110255,  9.21954446,  6.4807407 ]])

In [86]:
np.exp(a5)

array([[4.20121040e+25, 2.68811714e+43, 1.50609731e+35, 8.88611052e+06,
        1.73927494e+18],
       [7.89629602e+13, 9.49611942e+19, 6.56599691e+07, 1.17191424e+16,
        2.90488497e+13],
       [1.11286375e+36, 7.69478527e+23, 4.03428793e+02, 2.00855369e+01,
        1.95729609e+11],
       [5.83461743e+14, 7.20048993e+10, 1.69488924e+28, 2.09165950e+24,
        1.17191424e+16],
       [1.69488924e+28, 2.98095799e+03, 5.05239363e+31, 7.20048993e+10,
        1.31881573e+09],
       [5.83461743e+14, 2.23524660e+37, 3.83100800e+22, 8.22301271e+36,
        1.73927494e+18]])

In [87]:
np.log10(a5)

array([[1.77085201, 2.        , 1.90848502, 1.20411998, 1.62324929],
       [1.50514998, 1.66275783, 1.25527251, 1.56820172, 1.49136169],
       [1.91907809, 1.74036269, 0.77815125, 0.47712125, 1.41497335],
       [1.53147892, 1.39794001, 1.81291336, 1.74818803, 1.56820172],
       [1.81291336, 0.90308999, 1.86332286, 1.39794001, 1.32221929],
       [1.53147892, 1.93449845, 1.71600334, 1.92941893, 1.62324929]])

In [94]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [96]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1.7,10.7,2.5)

array([1.7, 4.2, 6.7, 9.2])

In [98]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [99]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [100]:
np.logspace(2,4,num=4, base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [101]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])